version: '3.4'
##### HOTFIXES
# sudo chown -R 1000:1000 ./dockers/elasticsearch/data   <<<< fix quyền docker quan trọng!
# docker compose up --build hoặc docker compose up -d --build --pull always --remove-orphans : khi cần Dockerfile chạy lại, để build lại!

services:
  elasticsearch:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        ES_VERSION: ${ES_VERSION}
    restart: on-failure
    ports:
      - 9200:9200
    #   - 9300:9300
    volumes:
      - ./data:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - cluster.routing.allocation.disk.threshold_enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - path.data=/usr/share/elasticsearch/data
    container_name: 'dev-elasticsearch'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        hard: -1
        soft: -1
    networks:
      - dev-network
      
  # kibana:
  #   container_name: kb-container
  #   image: docker.elastic.co/kibana/kibana:8.15.0
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://es-container:9200
  #   networks:
  #     - dev.elasticsearch
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - 5601:5601

networks:
  dev-network:
    driver: bridge